# -*- coding: utf-8 -*-
# ===== 網站內容都在這裡改，改完執行 python3 build.py 重新產生所有頁面 =====

SITE = {
    "name": "Chin-En Gau",
    "email": "gau88813@gmail.com",
    "imdb": "https://www.imdb.com/name/nm14132633/",
    "linkedin": "https://www.linkedin.com/in/chin-en-gau-492660231",
    "instagram": "https://www.instagram.com/chin_en_gau/",
    "reel": "https://youtu.be/Kb7IJWt5PzY?t=6",
    "resume": "Chin-En_Gau_Resume.pdf",
}

# ---------- 豎屏短劇（只放有海報的）----------
VERTICALS = [
 dict(slug="reborn-to-love-alpha-king", title="Reborn to Love Alpha King", year=2026, img="reborn-to-love.jpg",
      episodes=61, genres=["Romance","Werewolf","Revenge","Sweet Love"], ai=False,
      views="20.7M", rank="No.3", peak="2M views/day", extra_en="No.6 Top Searched", extra_zh="搜尋榜第六",
      syn_en="Betrayed and reborn, Chelsea Wharton strives to return to her former love and battles wits with malicious relatives who covet her inheritance, changing her fate amidst the dual crises of protecting her love and her legacy.",
      syn_zh="遭背叛後重生的 Chelsea Wharton 決心重回昔日戀人身邊，並與覬覦遺產的惡親戚鬥智鬥勇。在守護愛情與家業的雙重危機中，她親手改寫了自己的命運。"),
 dict(slug="time-to-cut-off-my-shameless-family", title="Time To Cut Off My Shameless Family", year=2025, img="time-to-cut-off-my-shameless-family.jpg",
      episodes=56, genres=["Revenge","Rebirth"], ai=False,
      views="19.6M", rank="No.1", peak="1M views/day", extra_en="", extra_zh="",
      syn_en="After discovering that her “perfect” foster sister Nancy uses a secret power to turn their family against her, Peggy is murdered. But she wakes up ten years in the past—the year her family first adopted Nancy. Now, she must expose the truth and finally break free from her toxic family.",
      syn_zh="Peggy 發現「完美」的養妹 Nancy 一直用神秘的能力讓全家與她為敵，卻在揭穿前慘遭殺害。再睜眼，她回到了十年前——家人剛收養 Nancy 的那一年。這一次，她要揭開真相，徹底擺脫這個有毒的家。"),
 dict(slug="the-war-god-returns-to-claim-his-family", title="The War God Returns to Claim His Family", year=2026, img="the-war-god-s-return.jpg",
      episodes=58, genres=["Urban","Secret Identity","Second-chance Love","Counterattack"], ai=False,
      views="13M", rank="No.2", peak="902K views/day", extra_en="", extra_zh="",
      syn_en="After being at war for five years, Jack Stone returns home, now secretly a billionaire war hero known as “The War God.” But upon reuniting with his family, he discovers his beloved daughter hates him and his wife has secretly divorced him and married his old rival: a crooked businessman who will stop at nothing to destroy Jack and steal his daughter away.",
      syn_zh="征戰五年後，Jack Stone 以人稱「戰神」的億萬富翁戰爭英雄身分低調返鄉。然而重逢的家人卻已面目全非：心愛的女兒恨他入骨，妻子早已悄悄離婚，改嫁給他的宿敵——一個不擇手段、誓要毀掉 Jack 並奪走他女兒的奸商。"),
 dict(slug="im-done-chasing-a-brat", title="I’m Done Chasing A Brat!", year=2026, img="i-m-done-chasing-a-brat.jpg",
      episodes=50, genres=["Comeback Story","Hidden Identity","Revenge","Rebirth"], ai=True,
      views="12.7M", rank="No.2", peak="", extra_en="", extra_zh="",
      syn_en="Joe, secret heir to the Havv fortune, loves Tina—his chauffeur’s daughter, a fake heiress who frames him and drives him off a rooftop. He wakes reborn before it all began. This time he exposes her, strips away every luxury he ever bought her, and crowns kind-hearted Anna at a billion-dollar banquet where Tina’s fraud collapses.",
      syn_zh="Havv 家族的隱藏繼承人 Joe 深愛著司機的女兒 Tina——一個冒牌千金，她陷害 Joe 並將他逼下天台。再醒來，一切尚未發生。這一次他揭穿她的謊言，收回為她砸下的所有奢華，並在一場十億美元的晚宴上讓 Tina 的騙局徹底崩塌，把王冠戴在善良的 Anna 頭上。"),
 dict(slug="the-loser-janitor-is-the-ultimate-legend", title="The Loser Janitor is the Ultimate Legend", year=2026, img="the-loser-janitor.jpg",
      episodes=52, genres=["Comeback Story","Counterattack","Revenge","War God"], ai=True,
      views="6.3M", rank="No.7", peak="", extra_en="", extra_zh="",
      syn_en="Twenty years ago, Grand Lord Cyril ended an alien invasion but lost his wife. He vanished into a janitor’s life, raising his son and refusing wealth or titles. After saving a girl, he’s set up on a date with her mother—a tycoon. Mocked as unworthy, he stays silent until he reveals his identity, humbling his tormentors. Then the aliens return.",
      syn_zh="二十年前，大領主 Cyril 終結了一場外星入侵，卻失去了妻子。他從此隱姓埋名成為清潔工，獨自扶養兒子，拒絕一切財富與頭銜。一次救了小女孩後，他被安排與女孩的母親——一位企業女強人——相親。面對眾人嘲諷，他始終沉默，直到亮出真實身分讓所有人低頭。而此時，外星人再度來襲。"),
 dict(slug="love-me-when-i-am-gone", title="Love Me When I Am Gone", year=2026, img="love-me-when-i-m-gone.jpg",
      episodes=60, genres=["Romance","Family Bonds","Second Chance"], ai=False,
      views="3.3M", rank="", peak="", extra_en="", extra_zh="",
      syn_en="To pay her father’s medical bills, Rosie marries Mason in place of her runaway twin sister for a three-year contract. Just as her devotion finally wins his affection, his first love returns, shattering her world. Enduring neglect and heartbreak, Rosie leaves him without looking back the moment the three years are up. By the time Mason learns the truth and regrets his actions, she is already gone.",
      syn_zh="為了支付父親的醫藥費，Rosie 代替逃婚的雙胞胎姊姊嫁給 Mason，簽下三年契約婚姻。就在她的付出終於換來他的心意時，他的初戀回來了，讓一切崩塌。忍受冷落與心碎的 Rosie 在三年期滿的那一刻頭也不回地離開。等到 Mason 明白真相、追悔莫及，她早已不在。"),
 dict(slug="high-card-hustle", title="High Card Hustle", year=2026, img="hign-card-hustle.jpg",
      episodes=53, genres=["Crime","Con","Revenge"], ai=True,
      views="291K", rank="", peak="", extra_en="", extra_zh="",
      syn_en="A retired gambling prodigy must repay an old debt when the daughter of the mentor who once took the fall for him comes begging for help. To win back her stolen inheritance, they must pull off a high-stakes con against a ruthless mob empire—only to discover they have been trapped in a deadly conspiracy, a game they cannot afford to lose.",
      syn_zh="一位金盆洗手的賭博天才，因當年替他頂罪的恩師之女前來求助而必須償還舊債。為了奪回她被侵吞的遺產，兩人要對一個冷血的黑幫帝國設下一場豪賭級的騙局——卻發現自己早已落入一場致命的陰謀，一場輸不起的遊戲。"),
]

# ---------- 電影 ----------
FILMS = [
 dict(slug="a-journey-of-jack-and-tom", title="A Journey of Jack (and Tom)", year=2026, kind_en="Feature · Comedy", kind_zh="長片 · 喜劇",
      role_en="Director · Writer · Cinematographer · Editor", role_zh="導演 · 編劇 · 攝影 · 剪接",
      runtime="83 min", status_en="Completed — in post-production", status_zh="已完成拍攝，後製中",
      hero="a-journey-of-jack-02.jpg", stills=["a-journey-of-jack-01.jpg","a-journey-of-jack-04.jpg","a-journey-of-jack-03.jpg"],
      laurels=["FilmNorth Inclusive & Socially Conscious Filmmaking Lab 2025","DI3 Fellowship","Lichtenstein–Reeves Fund"],
      syn_en="Two restless teens from Taiwan slip away to New York, chasing a dream of shooting a music video in Times Square—but the America they find is “slightly” nothing like the one they imagined.",
      syn_zh="兩個不安分的台灣少年偷偷溜到紐約，夢想在時代廣場拍一支 MV——但他們遇見的美國，跟想像中的「稍微」有點不一樣。",
      credits=[("Cast","Johnson Yeh, Kevin Cheng, Vivienne Yang, Yu-Ning Chang"),("Writers","Aleesha Dineros-Canuto, Chin-En Gau"),("Language","Mandarin, English")]),
 dict(slug="ride-with-delivery-workers", title="Ride with Delivery Workers", year=2025, kind_en="Feature Documentary", kind_zh="紀錄長片",
      role_en="Cinematographer · Additional Editor", role_zh="攝影 · 協力剪接",
      runtime="", status_en="Directed by Jing Wang", status_zh="導演：Jing Wang",
      hero="ride-with-delivery-worker-10.jpg", stills=[], poster="ride-with-delivery-worker-09.jpg",
      laurels=["Sundance Institute Documentary Fund","Gold House AAPI Renaissance Rally","Rooftop Film Festival","Jacob Burns Film Center Artist-in-Residence 2026"],
      syn_en="A lyrical, eight-year journey alongside New York City’s immigrant food-delivery workers—predominantly Chinese—as they fight for fair working conditions and the right to ride e-bikes without fines or confiscation. From the mayor’s e-bike crackdown through legalization and the pandemic, when the same essential workers were heroized and scapegoated at once, the film follows a community organizing for resilience, dignity and justice.",
      syn_zh="一段橫跨八年、如詩般的旅程，跟隨紐約市的移民外送員——多數為華人——爭取合理工作條件與合法騎乘電動自行車、不再被罰款沒收的權利。從市長的電動車掃蕩、合法化，到疫情期間這群「必要工作者」同時被歌頌又被指責，影片記錄了一個社群為韌性、尊嚴與正義而組織起來的過程。"),
 dict(slug="the-snow-is-singing", title="The Snow is Singing", year=2024, kind_en="Feature · Theatre-Film", kind_zh="長片 · 劇場電影",
      role_en="Director of Photography", role_zh="攝影指導",
      runtime="", status_en="Directed by Bimal Subedi · Happy Home Studios · Theatrical release in South Asia, 2026", status_zh="導演：Bimal Subedi · Happy Home Studios · 2026 年南亞院線上映",
      hero="the-snow-is-singing-23.jpg", stills=["the-snow-is-singing-17.jpg","the-snow-is-singing-19.jpg","the-snow-is-singing-21.jpg","the-snow-is-singing-22.jpg","the-snow-is-singing-18.jpg","the-snow-is-singing-20.jpg"],
      laurels=["The Gotham Film & Media Institute — Fiscal Sponsorship","Crew of 100+"],
      syn_en="An eight-year-old boy in a quiet Midwestern town begins to carry the unspoken memories of his grandparents’ forced displacement from Bhutan, as renewed fears of deportation force his family to confront a past they tried to bury. Young Ishir manifests the family’s suppressed trauma through his body, dreams and behaviour, as three generations of a Nepali-speaking Bhutanese refugee family face what they never spoke of.",
      syn_zh="在寧靜的美國中西部小鎮，八歲男孩開始承載祖父母被迫離開不丹、從未說出口的記憶；當被驅逐出境的恐懼再度籠罩，全家不得不面對他們試圖埋葬的過去。小男孩 Ishir 的身體、夢境與行為成了家族壓抑創傷的出口，三代尼泊爾語系不丹難民終於直視那些從未被言說的事。"),
 dict(slug="a-piece-of-memory", title="A Piece of Memory", year=2025, kind_en="Short · 2 min", kind_zh="短片 · 2 分鐘",
      role_en="Director · Writer · Cinematographer · Editor", role_zh="導演 · 編劇 · 攝影 · 剪接",
      runtime="1′59″", status_en="Mandarin · Taiwan", status_zh="國語 · 台灣",
      hero="a-piece-of-memory-05.jpg", stills=["a-piece-of-memory-06.jpg","a-piece-of-memory-07.jpg","a-piece-of-memory-08.jpg"],
      laurels=["★ Jury Award — MAX3MIN Very Short Film Festival 2025","Fargo Film Festival","Centre Film Festival"],
      syn_en="Grandma passed away when she was 95, but her presence still lingers in her house.",
      syn_zh="奶奶在九十五歲那年離開了，但她的氣息仍留在那棟房子裡。",
      note_en="Director’s note — It took me a while to gather the courage to visit the apartment where she used to live. After arriving, the eerily silent apartment seemed to come alive with faint sounds.",
      note_zh="導演的話——我花了好一陣子才鼓起勇氣回到她生前住的公寓。踏進去之後，那間安靜得詭異的屋子，彷彿被細微的聲響重新喚醒。"),
 dict(slug="so-you-may-not-forget-me", title="So You May Not Forget Me", year=2024, kind_en="Short · 11 min", kind_zh="短片 · 11 分鐘",
      role_en="Director · Writer · Cinematographer · Editor", role_zh="導演 · 編劇 · 攝影 · 剪接",
      runtime="11 min", status_en="", status_zh="",
      hero="so-you-may-not-forget-me-11.jpg", stills=["so-you-may-not-forget-me-12.jpg","so-you-may-not-forget-me-13.jpg"],
      laurels=["Premiere — Film at Lincoln Center 2024","Centre Film Festival"],
      syn_en="Gabby, an 18-year-old who had a huge fight with her boyfriend last night, has to spend the day caring for her grandmother, who has Alzheimer’s. As she does, long-lost memories slowly emerge.",
      syn_zh="十八歲的 Gabby 昨晚才跟男友大吵一架，今天卻得照顧患有阿茲海默症的奶奶。在陪伴的過程中，那些早已遺失的記憶慢慢浮現。",
      credits=[("Cast","Maya Borhaug, Susan Kirby, Trí Lê")]),
 dict(slug="the-expert-of-loneliness", title="The Expert of Loneliness", year=2023, kind_en="Short", kind_zh="短片",
      role_en="Director · Writer · Cinematographer · Editor", role_zh="導演 · 編劇 · 攝影 · 剪接",
      runtime="", status_en="", status_zh="",
      hero="the-expert-of-loniness-15.jpg", stills=["the-expert-of-loniness-14.jpg","the-expert-of-loniness-16.jpg"],
      laurels=["Premiere — Film at Lincoln Center 2023"],
      syn_en="Mr. Han, a middle-aged immigrant, invites his brother to join him for a Lunar New Year dinner. While the colleagues he also invited don’t enjoy the food, his brother—his only relative here—is preoccupied with his own family.",
      syn_zh="中年移民韓先生邀請弟弟一起吃年夜飯。他同時邀來的同事們吃得興致缺缺，而弟弟——他在這裡唯一的親人——心思全在自己的家庭上。",
      credits=[("Cast","Carl Bindman, Brian Sterling Chan, Michelle Concha-Herko, Guang Xu Jason Xiang")]),
 dict(slug="the-team", title="The Team", year=2023, kind_en="Short · 4 min", kind_zh="短片 · 4 分鐘",
      role_en="Director · Writer · Cinematographer · Editor", role_zh="導演 · 編劇 · 攝影 · 剪接",
      runtime="4 min", status_en="", status_zh="",
      hero="", stills=[],
      laurels=["Flint Youth Film Festival","JCAL 10 Minute Film Festival","Lift-Off Sessions — First-Time Filmmaker Session","Quarterfinalist — Student World Impact Film Festival"],
      syn_en="Emma, an 11-year-old girl, wants ice cream for her birthday—but has to earn it with her own effort.",
      syn_zh="十一歲的 Emma 想在生日那天吃冰淇淋——但她得靠自己的努力去換。",
      credits=[("Cast","Michelle Concha-Herko, Olivia Herko")]),
 dict(slug="miss-mermaid", title="Miss Mermaid", year=2024, kind_en="Feature", kind_zh="長片",
      role_en="Co-Producer", role_zh="聯合製片",
      runtime="", status_en="", status_zh="",
      hero="", stills=[],
      laurels=["Tribeca Festival 2024 — Work-in-Progress showcase"],
      syn_en="", syn_zh=""),
 dict(slug="big-scene", title="Big Scene", year=2026, kind_en="Short · 9 min · Drama", kind_zh="短片 · 9 分鐘 · 劇情",
      role_en="Director of Photography · Co-Producer", role_zh="攝影指導 · 聯合製片",
      runtime="9 min", status_en="Directed by Yu Shao Chen · Completed", status_zh="導演：Yu Shao Chen · 已完成",
      hero="", stills=[], laurels=[],
      syn_en="Amid a protest movement, a woman believes that she and her fellow protesters can be extraordinary rebel heroes—but after living through the entire protest, she becomes disillusioned.",
      syn_zh="在一場抗爭運動中，一名女子深信自己與同伴能成為非凡的反抗英雄——然而當她真正走完整場抗爭，卻只剩下幻滅。",
      credits=[("Cast","Trí Lê, Rengu Zhang")]),
 dict(slug="its-relative", title="It’s Relative", year=2023, kind_en="Short · 6 min", kind_zh="短片 · 6 分鐘",
      role_en="Cinematographer", role_zh="攝影",
      runtime="6 min", status_en="Directed by Nnamdi Nwosa", status_zh="導演：Nnamdi Nwosa",
      hero="", stills=[], laurels=["Official Selection — Flickers’ Rhode Island International Film Festival"],
      syn_en="Chinomso meets with his close cousin, only to realize the two of them have grown far apart. Their once-strong bond, forged through decades of martial-arts practice, is tested—and he must decide whether to keep with family tradition and stay close, or break away.",
      syn_zh="Chinomso 與親近的堂兄弟重逢，卻發現兩人早已漸行漸遠。數十年習武建立起的情誼受到考驗，他必須決定：是遵循家族傳統維繫關係，還是就此分道揚鑣。",
      credits=[("Cast","Charles Etubiebi, Casimir Gregory")]),
 dict(slug="the-black-side-of-the-river", title="The Black Side of the River", year=2026, kind_en="Short · Drama · Fantasy", kind_zh="短片 · 劇情 · 奇幻",
      role_en="Cinematographer", role_zh="攝影",
      runtime="", status_en="Directed by Samundra Raj Ghimire · In post-production", status_zh="導演：Samundra Raj Ghimire · 後製中",
      hero="", stills=[], laurels=[],
      syn_en="After losing her grandmother’s generational home to gentrification, 16-year-old Harriet Washington plunges into an underwater realm to ask Mami Wata for a chance to reclaim it.",
      syn_zh="祖母世代相傳的老家因仕紳化而失去後，十六歲的 Harriet Washington 潛入水下世界，向水神 Mami Wata 祈求一個奪回家園的機會。",
      credits=[("Cast","Kaylee Marcks, Sharondra Mealey, Dora Shulman")]),
 dict(slug="method-in-the-madness", title="Method in the Madness", year=2023, kind_en="Short · 5 min · Comedy", kind_zh="短片 · 5 分鐘 · 喜劇",
      role_en="Cinematographer", role_zh="攝影",
      runtime="5 min", status_en="Directed by Sri Ram Burgula", status_zh="導演：Sri Ram Burgula",
      hero="", stills=[], laurels=[],
      syn_en="", syn_zh="",
      credits=[("Cast","Daniel Joey Oakley")]),
 dict(slug="the-ones-before", title="The Ones Before", year=2021, kind_en="Short · 代代", kind_zh="短片 · 《代代》",
      role_en="Executive Director · Editor", role_zh="執行導演 · 剪接",
      runtime="", status_en="", status_zh="",
      hero="the-ones-before-02.jpg", stills=["the-ones-before-01.jpg","the-ones-before-03.jpg"], poster="the-ones-before-poster.jpg",
      laurels=["Taitung County Government Film Production Grant · 台東縣政府拍攝補助"],
      syn_en="Li Yan meets two women. One is the question she has always carried about who she is; the other is its answer.",
      syn_zh="李燕遇見了兩個人，她們是李燕對自我身分的疑問與解答。"),
]

# ---------- 新聞 / 專訪 ----------
PRESS = [
 dict(outlet="世界新聞網 World Journal", date="2026-04-30", lang="zh",
      title_en="Taiwanese producer Chin-En Gau: new-immigrant storytelling, and verticals as the opening",
      title_zh="台灣製片高靖恩：新移民敘事 短劇成契機",
      url="https://www.worldjournal.com/wj/story/121390/9473195",
      blurb_en="A profile on the rise of vertical short drama in the U.S. as seen from inside DramaBox — the three-minute, emotion-first format, its largely female audience, and the door it has opened for Chinese-speaking newcomers in the industry.",
      blurb_zh="從 DramaBox 內部觀察短劇在美國的興起：三分鐘直式、情緒導向的敘事形式、以女性為主的觀眾，以及它為華人新移民打開的影視產業缺口。",
      quote_en="", quote_zh="「這是 1895 年電影誕生以來，第一次由華人引起的娛樂潮流。」"),
 dict(outlet="CanvasRebel Magazine", date="2024-03-28", lang="en",
      title_en="Meet Chin-En Gau", title_zh="Meet Chin-En Gau",
      url="https://canvasrebel.com/meet-chin-en-gau/",
      blurb_en="On the project that meant the most: a short born from his grandmother’s final months with Alzheimer’s, the logline “Forgetting is happier,” and why he tells the stories people usually overlook.",
      blurb_zh="談最有意義的一部作品：源自奶奶罹患阿茲海默症的最後幾個月、那句「遺忘是幸福的」，以及為什麼他想說那些常被忽略的人的故事。",
      quote_en="“Forgetting is happier.”", quote_zh=""),
 dict(outlet="大紀元 The Epoch Times", date="2023-02-08", lang="zh",
      title_en="Taiwanese film student in New York casts a short on Chinese immigrants",
      title_zh="紐約台灣留學生拍華人移民短片 物色演員",
      url="https://www.epochtimes.com/b5/23/2/8/n13925095.htm",
      blurb_en="An early report on the short that became The Expert of Loneliness — a ten-minute film about the loneliness and longing for family of a middle-aged Chinese immigrant in America — and the hope of building a bridge between East and West.",
      blurb_zh="報導《The Expert of Loneliness》前身的籌備：一部十分鐘短片，探討華人移民在美國的孤獨感與對親情的渴望，並期望成為東西文化溝通的橋梁。",
      quote_en="", quote_zh=""),
 dict(outlet="CanvasRebel Magazine", date="2024-12-02", lang="en",
      title_en="Conversations with Chin-En Gau", title_zh="Conversations with Chin-En Gau",
      url="https://canvasrebel.com/conversations-with-chin-en-gau/",
      blurb_en="On stealing the family camera as a kid, finding a voice among talented classmates at art school, the films that reveal “the other side of people,” and how short-form video is changing the way audiences watch stories.",
      blurb_zh="從小時候偷拿家裡相機說起，談在藝術大學被同儕挑戰後如何找到自己的路、那些「揭露人另一面」的作品，以及短影音如何改變觀眾看故事的方式。",
      quote_en="“For me, film is all about the story.”", quote_zh=""),
 dict(outlet="Bold Journey Magazine", date="2024-07-23", lang="en",
      title_en="Meet Chin-En Gau", title_zh="Meet Chin-En Gau",
      url="https://boldjourney.com/meet-chin-en-gau/",
      blurb_en="An interview on overcoming creative blocks, the three qualities that matter most to a filmmaker — sincerity, communication and an open mind — and learning to slow down.",
      blurb_zh="談如何走出創作瓶頸、創作者最重要的三種特質——真誠、溝通與開放——以及學會放慢腳步。",
      quote_en="“Creativity thrives on flexibility and adaptation.”", quote_zh=""),
 dict(outlet="Film Sessions™ Podcast · Student World Impact Film Festival", date="", lang="en",
      title_en="Chin-En Gau: Inspirational Interview", title_zh="Chin-En Gau: Inspirational Interview",
      url="https://music.amazon.com/es-co/podcasts/454cfd0f-31c5-4ff0-802f-73429a015ac6/episodes/2700e019-d695-4260-961f-8aa85bb866b6/film-sessions%E2%84%A2-podcast-chin-en-gau-inspirational-interview",
      blurb_en="Podcast conversation hosted by Kimmi Breece for the Student World Impact Film Festival, following The Team’s quarterfinalist selection.",
      blurb_zh="Student World Impact Film Festival 的 Podcast 訪談，主持人 Kimmi Breece；《The Team》入選該影展八強後受邀。",
      quote_en="", quote_zh=""),
]
